In [2]:
import numpy as np

In [11]:
gold = [4, "6", "CSE", "doc"]

In [12]:
gold[0]

4

In [13]:
int(gold[1])

6

## Q1

- Part 1: `type(prices[0])` → `float`
- Part 2: `type(calories[0])` → `int`
- Part 3: `min(prices / calories)` is the cost per calorie of the product with the lowest cost per calorie
- Part 4: False

## Q2

- Part 1: `bass * tuna` → `"55"`
- Part 2: `int(sword[0])` errors (can't convert `"4.0"` directly to int)
- Part 3: `gold[3].replace("o", "s").upper() + str(gold[0] + int(gold[1]))` → `"DSC10"`

## Q3

In [3]:
array_1 = np.arange(1, 7, 2.5)
array_1

array([1. , 3.5, 6. ])

In [4]:
array_2 = np.arange(8, 2, -2)
array_2

array([8, 6, 4])

In [ ]:
array_2.

In [12]:
(array_1 * array_2)

array([ 8., 21., 24.])

`(np.arange(1, 7, 2.5) * np.arange(8, 2, -2))[2]` → `24.0`

## Q4

In [5]:
peach = np.arange(1, 10)

In [ ]:
peach.

In [9]:
string_b = "4.0"

In [10]:
float(string_b)

4.0

In [7]:
int(float(string_b))

4

In [8]:
int(string_b)

ValueError: invalid literal for int() with base 10: '4.0'

In [14]:
import numpy as np

In [17]:
type("4.0")

str

In [18]:
type(4.0)

float

In [19]:
type("asjdofihu98380")

str

In [20]:
list_1 = ["4.0", 4.0, "asdfgu", 12]

In [23]:
array_1 = np.array(list_1)
array_1

array(['4.0', '4.0', 'asdfgu', '12'], dtype='<U32')

- Part 1 (using array methods): `peach.max() - peach.min()`
- Part 2 (without methods/functions): `peach[-1] - peach[0]`
- Part 3: The spread of `peach` is **always less than** the value of `y - x`

## Q5

- Part 1: `penguin = np.arange(5, 25, 4)` (end can be any value in (21, 25])
- Part 2: `x = 2`, `y` = any value in (8, 10], `z = 5`

## Q6

Context: `sky` DataFrame — each row is a skyscraper; index = name (string), columns: `'material'` (str), `'city'` (str), `'floors'` (int), `'height'` (float), `'year'` (int)

- Part 1: `sky.sort_values('height')` → `DataFrame`
- Part 2: `sky.sort_values('height').get('material').loc[0]` → `error` (index has building names, not integers)
- Part 3: `sky.sort_values('height').get('material').iloc[0]` → `string`
- Part 4: `sky.get('floors').max()` → `int or float`
- Part 5: `sky.index[0]` → `string`

## Q7

- Part 1 (name of tallest skyscraper): `sky.sort_values(by='height', ascending=False).index[0]`
- Part 2 (average number of floors): `sky.get('floors').mean()`

## Q8

- Part 1: `students.get("Overall")` → `Series`
- Part 2: `students.get("PID")` → `this errors` (PID is the index, not a column)
- Part 3: `x = "Animal"`, `y = "A12345678"`, `z = 5`
- Part 4: Only `z` would need to change (`.loc` uses index label, `.iloc` uses position)

## Q9

`sports.index[1]` evaluates to `'basketball'`

## Q10

- Part 1: **False** — there could be ties, so employee 2476 is not necessarily *greater than* all others
- Part 2: **Error complaining about something else** — `assign` result is not saved, so `'start'` column doesn't exist when `sort_values` is called